"""Initial migration.

Revision ID: 44e0cdf5c8b0
Revises: 
Create Date: 2021-04-01 16:43:15.991992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e0cdf5c8b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=25), nullable=False),
    sa.Column('card_platform', sa.String(length=55), nullable=False),
    sa.Column('card_info', sa.String(length=150), nullable=False),
    sa.Column('card_price', sa.Integer(), nullable=True),
    sa.Column('card_service', sa.Integer(), nullable=True),
    sa.Column('card_image_url', sa.String(length=180), nullable=False),
    sa.Column('card_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('type')
    # ### end Alembic commands ###
